# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
#link_with 'BabyTunesTests', 'BabyTunesTests'
use_frameworks!

target 'BabyTunes' do
pod 'Swinject', '2.1.0'
pod 'RealmSwift'
pod 'RxSwift', '~> 4.0'
pod 'Parse'
pod 'AAViewAnimator'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end