# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
link_with 'BabyTunesTests', 'BabyTunesTests'
use_frameworks!

target 'BabyTunes' do
pod 'SwiftyJSON', '~> 2.2.0'
pod 'Alamofire', '~> 1.2'
end

target 'BabyTunesTests' do

pod 'FBSnapshotTestCase', :git => 'https://github.com/delannoyk/ios-snapshot-test-case'
pod 'SwiftHamcrest'

end

